Repository CAN-D/CAN-D, pull requests merged in 2019-02, with the labels that each got.

#27 Adds proj dir to Makefile
  CAN-D/Makefile
Labels: Firmware

#28 Attempt to get the jenkins builder running
  CAN-D/Jenkinsfile
Labels: Support Software

#38 Update Pin IOs for Buttons and LEDs
  CAN-D/Drivers/BSP/Inc/stm32303c_custom.h
  CAN-D/Drivers/BSP/Src/stm32302c_custom.c
  CAN-D/Src/bridge.c
Labels: Firmware

#45 Add UART-GPS Interface Driver
  CAN-D/Drivers/BSP/Inc/stm32302c_custom.h
  CAN-D/Drivers/BSP/Inc/stm32302c_custom_gps.h
  CAN-D/Drivers/BSP/Inc/stm32302c_custom_sd.h
  CAN-D/Drivers/BSP/Src/stm32302c_custom.c
  CAN-D/Drivers/BSP/Src/stm32302c_custom_gps.c
  CAN-D/Drivers/BSP/Src/stm32302c_custom_sd.c
  CAN-D/Inc/bridge.h
  CAN-D/Inc/usart.h
  CAN-D/Makefile
  CAN-D/Src/bridge.c
  CAN-D/Src/can.c
  CAN-D/Src/freertos.c
  CAN-D/Src/main.c
  CAN-D/Src/sd_diskio.c
  CAN-D/Src/stm32f3xx_it.c
  CAN-D/Src/usart.c
Labels: Firmware

#48 Fix Compile Warnings
  CAN-D/Drivers/BSP/Src/stm32302c_custom.c
  CAN-D/Src/bridge.c
Labels: Firmware

#46 Makes all warnings errors.
  CAN-D/Makefile
Labels: Firmware, enhancement

#50 Change GPS setting to RMC only
  CAN-D/Drivers/BSP/Src/stm32302c_custom_gps.c
  CAN-D/Inc/bridge.h
  CAN-D/Src/bridge.c
  CAN-D/Src/freertos.c
  CAN-D/Src/stm32f3xx_it.c
Labels: Firmware

#52 Apply formatter again
  CAN-D/Drivers/BSP/Src/stm32302c_custom_gps.c
  CAN-D/Drivers/BSP/Src/stm32302c_custom_sd.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_can.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_dma.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_flash.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_flash_ex.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pcd_ex.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rtc.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rtc_ex.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_spi_ex.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_tim.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_tim_ex.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_uart.c
  CAN-D/Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_uart_ex.c
  CAN-D/Middlewares/Third_Party/FatFs/doc/img/app1.c
  CAN-D/Middlewares/Third_Party/FatFs/doc/img/app2.c
  CAN-D/Middlewares/Third_Party/FatFs/doc/img/app3.c
  CAN-D/Middlewares/Third_Party/FatFs/doc/img/app4.c
  CAN-D/Src/bridge.c
  CAN-D/Src/can.c
  CAN-D/Src/fatfs.c
  CAN-D/Src/freertos.c
  CAN-D/Src/gpio.c
  CAN-D/Src/main.c
  CAN-D/Src/sd_diskio.c
  CAN-D/Src/stm32f3xx_hal_msp.c
  CAN-D/Src/stm32f3xx_hal_timebase_tim.c
  CAN-D/Src/stm32f3xx_it.c
  CAN-D/Src/system_stm32f3xx.c
  CAN-D/Src/tim.c
  CAN-D/Src/usb_device.c
  CAN-D/Src/usbd_cdc_if.c
  CAN-D/Src/usbd_conf.c
  CAN-D/Src/usbd_desc.c
Labels: Firmware

#54 Add ability to write to SD card via FatFS
  CAN-D/Inc/bridge.h
  CAN-D/Inc/fatfs.h
  CAN-D/Src/bridge.c
  CAN-D/Src/can.c
  CAN-D/Src/fatfs.c
  CAN-D/Src/freertos.c
  CAN-D/Src/main.c
Labels: Firmware
